CREATE DATABASE IF NOT EXISTS quiz_platform_db;
USE quiz_platform_db;

CREATE TABLE IF NOT EXISTS users(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(150) UNIQUE NOT NULL,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('ADMIN','CREATOR','PARTICIPANT') NOT NULL,
 active BOOLEAN DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quizzes(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(200) NOT NULL,
 description TEXT,
 duration_minutes INT NOT NULL,
 status ENUM('PENDING','APPROVED','REJECTED') DEFAULT 'PENDING',
 creator_id BIGINT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(creator_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 quiz_id BIGINT NOT NULL,
 question_text TEXT NOT NULL,
 correct_option INT NOT NULL,
 FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS question_options(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 question_id BIGINT NOT NULL,
 option_order INT NOT NULL,
 option_text VARCHAR(500) NOT NULL,
 FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS quiz_attempts(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT NOT NULL,
 quiz_id BIGINT NOT NULL,
 total_questions INT NOT NULL,
 correct_answers INT NOT NULL,
 score INT NOT NULL,
 percentage INT NOT NULL,
 attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS attempt_answers(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 attempt_id BIGINT NOT NULL,
 question_id BIGINT NOT NULL,
 selected_option INT NOT NULL,
 FOREIGN KEY(attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,
 FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 sender_id BIGINT NOT NULL,
 receiver_id BIGINT NOT NULL,
 message_text TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(receiver_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reminders(
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 user_id BIGINT NOT NULL,
 title VARCHAR(200) NOT NULL,
 reminder_text VARCHAR(500),
 reminder_time DATETIME,
 is_read BOOLEAN DEFAULT FALSE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS system_settings(
 setting_key VARCHAR(100) PRIMARY KEY,
 setting_value VARCHAR(500) NOT NULL
);
